import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { GHOSTS_TEAMS, GHOSTS_PLAYERS, AW_TEAMS, AW_PLAYERS } from "../src/data/historicalRosters.js";
import { createInitialStandings } from "../src/engine/standingsEngine.js";
import { ensureFourPlayerRosters } from "../src/engine/rosterIntegrity.js";
import { findPlayerLocation, getPlayerStatus, getTeamRoster, searchPlayers } from "../src/utils/playerLocation.js";
let pass=0; const check=(n,c,d="")=>{assert.ok(c,`${n}${d?` — ${d}`:""}`); pass++; console.log(`✓ ${n}${d?` (${d})`:""}`)};
console.log("═══ Player Visibility Diagnostic ═══\n");
check("League Rosters screen/component exists", existsSync("src/components/LeagueRosters.jsx"));
const app=readFileSync("src/App.jsx","utf8"), side=readFileSync("src/components/DynastySidebar.jsx","utf8"), comp=readFileSync("src/components/LeagueRosters.jsx","utf8");
check("League Rosters is reachable from the sidebar", app.includes("LeagueRosters") && side.includes("League Rosters"));
check("League Rosters search UI is present", comp.includes("Player Finder") && comp.includes("searchPlayers"));
let state=ensureFourPlayerRosters({gameName:"Cod Dynasty",currentEraId:"ghosts",currentGameTitle:"Call of Duty: Ghosts",seasonLabel:"2013/14",userTeamId:"optic_gaming",teams:GHOSTS_TEAMS.map(t=>({...t})),activeTeams:GHOSTS_TEAMS.map(t=>t.id),inactiveTeams:[],players:GHOSTS_PLAYERS.map(p=>({...p,status:p.teamId?"active":"free_agent",currentStatus:p.teamId?"active":"free_agent"})),freeAgents:[],standings:createInitialStandings(GHOSTS_TEAMS),eventCalendar:[],playerRegistry:Object.fromEntries(GHOSTS_PLAYERS.map(p=>[p.id,{...p,currentStatus:p.teamId?"active":"free_agent",currentTeamId:p.teamId||null}]))},"ghosts");
check("All active teams are visible", state.activeTeams.length===state.teams.length);
check("Every active team roster can be inspected", state.activeTeams.every(id=>getTeamRoster(state,id).length>0));
check("Every active team shows roster count", comp.includes("Roster") && comp.includes("/4"));
for (const name of ["Crimsix","C6","Karma","TeePee"]) check(`Search can locate ${name}`, findPlayerLocation(state,name).found);
check("FormaL/Formal search is alias-safe", findPlayerLocation(state,"Formal").found && findPlayerLocation(state,"FormaL").playerId===findPlayerLocation(state,"Formal").playerId);
const released={...state, players:state.players.map(p=>p.displayName==="Crimsix"?{...p,teamId:null,status:"free_agent",currentStatus:"free_agent"}:p), freeAgents:[...state.freeAgents, state.players.find(p=>p.displayName==="Crimsix")]};
check("Search reports Free Agency status correctly", findPlayerLocation(released,"C6").status==="free_agent");
const inactive={...state, playerRegistry:{...state.playerRegistry, test_inactive:{id:"test_inactive",displayName:"Inactive Guy",currentStatus:"inactive"}}};
check("Search reports inactive/retired status correctly if applicable", findPlayerLocation(inactive,"Inactive Guy").status==="inactive");
check("No player in the registry has unknown status", Object.values(state.playerRegistry).every(p=>["active","free_agent","inactive","retired"].includes(getPlayerStatus(p,findPlayerLocation(state,p.id).assignments))));
check("No active player disappears from all locations", state.players.filter(p=>p.teamId).every(p=>findPlayerLocation(state,p.id).found));
const dup={...state, players:[...state.players,{...state.players.find(p=>p.displayName==="Karma"),teamId:"envy"}]};
check("Duplicate active assignments are reported", findPlayerLocation(dup,"Karma").duplicateAssignments.length>1);
check("No Modern CDL or Challengers are required", !comp.toLowerCase().includes("challenger") && !comp.includes("CDL"));
let awPlayers=AW_PLAYERS.map(p=>({...p,status:p.teamId?"active":"free_agent",currentStatus:p.teamId?"active":"free_agent"}));
for (const p of state.players) if(!awPlayers.some(a=>String(a.name).toLowerCase()===String(p.name).toLowerCase())) awPlayers.push({...p,teamId:null,status:"free_agent",currentStatus:"free_agent",previousTeamId:p.teamId});
let aw=ensureFourPlayerRosters({...state,currentEraId:"advanced_warfare",currentGameTitle:"Call of Duty: Advanced Warfare",seasonLabel:"2014/15",teams:AW_TEAMS.map(t=>({...t})),activeTeams:AW_TEAMS.map(t=>t.id),players:awPlayers,freeAgents:awPlayers.filter(p=>!p.teamId),standings:createInitialStandings(AW_TEAMS)},"advanced_warfare");
aw.playerRegistry=Object.fromEntries(aw.players.map(p=>[p.id,{...p,currentStatus:p.teamId?"active":(p.currentStatus||"free_agent"),currentTeamId:p.teamId||null}]));
for (const name of ["Crimsix","FormaL","Karma","TeePee"]) check(`${name} has a clear AW transition location`, findPlayerLocation(aw,name).found && findPlayerLocation(aw,name).status!=="missing", findPlayerLocation(aw,name).currentTeamName || findPlayerLocation(aw,name).status);
console.log(`\nPlayer visibility diagnostic passed (${pass} checks).`);
