import assert from "node:assert/strict";
import { GHOSTS_TEAMS, GHOSTS_PLAYERS } from "../src/data/historicalRosters.js";
import { GHOSTS_EVENTS } from "../src/data/ghostsEventCalendar.js";
import { createInitialStandings } from "../src/engine/standingsEngine.js";
import { createHistoricalEventState } from "../src/engine/historicalEventEngine.js";
import { ensureFourPlayerRosters, getRosterIntegrityProblems } from "../src/engine/rosterIntegrity.js";
let pass=0; const check=(n,c,d="")=>{assert.ok(c,`${n}${d?` — ${d}`:""}`); pass++; console.log(`✓ ${n}${d?` (${d})`:""}`)};
console.log("═══ Roster Integrity Diagnostic ═══\n");
const userTeamId="optic_gaming";
let state=ensureFourPlayerRosters({currentEraId:"ghosts",userTeamId,teams:GHOSTS_TEAMS.map(t=>({...t})),activeTeams:GHOSTS_TEAMS.map(t=>t.id),players:GHOSTS_PLAYERS.map(p=>({...p})),freeAgents:[],standings:createInitialStandings(GHOSTS_TEAMS)},"ghosts");
check("Fresh Ghosts dynasty has all active teams at 4 players", state.activeTeams.every(id=>state.players.filter(p=>p.teamId===id).length===4));
check("User team has 4 players", state.players.filter(p=>p.teamId===userTeamId).length===4);
check("No active team has fewer than 4", !state.activeTeams.some(id=>state.players.filter(p=>p.teamId===id).length<4));
const activeIds=state.players.filter(p=>p.teamId).map(p=>p.id); check("No player is active on multiple teams", activeIds.length===new Set(activeIds).size);
const eventState=createHistoricalEventState(GHOSTS_EVENTS[0],state.teams,state.players,state.standings,userTeamId,1234);
check("Every first event team has 4 players", eventState.field.every(t=>state.players.filter(p=>p.teamId===t.teamId).length===4));
const released=state.players.find(p=>p.teamId!==userTeamId); let thin={...state,players:state.players.map(p=>p.id===released.id?{...p,teamId:null,previousTeamId:p.teamId,status:"freeAgent",currentStatus:"freeAgent"}:p)}; thin=ensureFourPlayerRosters(thin,"ghosts");
check("Free Agency contains valid unsigned players if displaced players exist", thin.freeAgents.every(p=>!p.teamId));
const userDrop=state.players.find(p=>p.teamId===userTeamId); const fa=state.players.find(p=>p.teamId!==userTeamId); let signState={...state,players:state.players.map(p=>p.id===userDrop.id?{...p,teamId:null,status:"freeAgent",currentStatus:"freeAgent"}:p.id===fa.id?{...p,teamId:null,status:"freeAgent",currentStatus:"freeAgent"}:p),freeAgents:[{...userDrop,teamId:null},{...fa,teamId:null}]};
check("User can sign a free agent when roster has 3 players", signState.players.filter(p=>p.teamId===userTeamId).length===3 && signState.freeAgents.length>=1);
const beforeOvr=signState.players.filter(p=>p.teamId===userTeamId).reduce((s,p)=>s+p.overall,0)/3; const signee=signState.freeAgents.find(p=>p.id!==userDrop.id)||signState.freeAgents[0]; signState={...signState,players:signState.players.map(p=>p.id===signee.id?{...p,teamId:userTeamId,status:"active",currentStatus:"active"}:p),freeAgents:signState.freeAgents.filter(p=>p.id!==signee.id)};
check("Signing a free agent removes them from Free Agency", !signState.freeAgents.some(p=>p.id===signee.id));
check("Signing a free agent restores roster to 4", signState.players.filter(p=>p.teamId===userTeamId).length===4);
const afterOvr=signState.players.filter(p=>p.teamId===userTeamId).reduce((s,p)=>s+p.overall,0)/4; check("Team OVR recalculates after signing", Number.isFinite(afterOvr) && afterOvr!==beforeOvr);
check("Roster integrity passes", getRosterIntegrityProblems(ensureFourPlayerRosters(signState,"ghosts"),"ghosts").length===0);
console.log(`\nRoster integrity diagnostic passed (${pass} checks).`);
