import assert from "node:assert/strict";
import { GHOSTS_TEAMS, GHOSTS_PLAYERS } from "../src/data/historicalRosters.js";
import { GHOSTS_EVENTS } from "../src/data/ghostsEventCalendar.js";
import { createInitialStandings } from "../src/engine/standingsEngine.js";
import { createHistoricalEventState, getNextPendingMatch, simulateMatch } from "../src/engine/historicalEventEngine.js";
import { ensureFourPlayerRosters } from "../src/engine/rosterIntegrity.js";
let pass=0; const check=(n,c,d="")=>{assert.ok(c,`${n}${d?` — ${d}`:""}`); pass++; console.log(`✓ ${n}${d?` (${d})`:""}`)};
console.log("═══ Historical Event Stability Diagnostic ═══\n");
let state=ensureFourPlayerRosters({currentEraId:"ghosts",userTeamId:"optic_gaming",teams:GHOSTS_TEAMS,activeTeams:GHOSTS_TEAMS.map(t=>t.id),players:GHOSTS_PLAYERS.map(p=>({...p})),freeAgents:[],standings:createInitialStandings(GHOSTS_TEAMS)},"ghosts");
const beforeCount=state.players.length; const event=GHOSTS_EVENTS[0]; let ev=createHistoricalEventState(event,state.teams,state.players,state.standings,state.userTeamId,999);
check("No event starts with a team below 4 players", ev.field.every(t=>state.players.filter(p=>p.teamId===t.teamId).length===4));
const teamIds=new Set(ev.field.map(t=>t.teamId)); check("All event matches reference valid teams", ev.matches.every(m=>teamIds.has(m.teamA?.teamId)&&teamIds.has(m.teamB?.teamId)));
check("All event teams have valid 4-player rosters", [...teamIds].every(id=>state.players.filter(p=>p.teamId===id).length===4));
while(ev.status!=="completed") ev=simulateMatch(ev,getNextPendingMatch(ev).id,event,state.userTeamId);
check("Event completion does not delete players", state.players.length===beforeCount);
console.log(`\nHistorical event stability diagnostic passed (${pass} checks).`);
